### ISSUE TITLE
`%H` yields an empty string for hard-links

### ISSUE THREAD

**Issue by cipriancraciun** [miekg/rdup#10]
It seems that on the latest `rdup` (1.1.14) the format flag `%H` yields an empty string for hard-links, meanwhile for all other file types it yields an all zero hash.

**Comment by dpc** [comment]
This seems fixed in ba1ead7b503942595a74f137564a7c1c18aec8f2 . I've briefly tested it and both original file and it's hardlink the sha is being printed.

Can be closed, I believe @miekg .
