### ISSUE TITLE
`%s` 2GiB wrapping

### ISSUE THREAD

**Issue by cipriancraciun** [miekg/rdup#11]
It seems that for the latest `rdup` (1.1.14) the size (as per `%s` formatting option) behaves like a signed 32 bit counter, thus yielding negative (or wrong) values for all files over 2GiB.

(The hash is good though.)

**Comment by dpc** [comment]
@miekg OK to close?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [rdup] `%s` 2GiB wrapping (#11)..." ]
>@miekg OK to close?

Is it fixed? If so, yes

**Comment by dpc** [comment]
IMO it was fixed in 460cecaa96c16635658a7a1591f3d28645f8f709
