### ISSUE TITLE
Libarchive api update build fix

### ISSUE THREAD

**Issue by yoshi314** [miekg/rdup#14]
There is a minor change required for updated libarchive api in rdup-tr

sed -i -e 's/archive_write_finish/archive_write_free/g' rdup-tr.c

This allows to build package on more recent opensuse systems, build results are here : https://build.opensuse.org/package/show/home:wengo/rdup

Without this modification rdup would only build on 12.3 .

**Comment by dpc** [comment]
This looks stale, probably fixed / irrelevant by now.
