### ISSUE TITLE
Failed to make socket.

### ISSUE THREAD

**Issue by dpc** [miekg/rdup#19]
```
** rdup-up: Failed to make socket `/home/dpc/tmp/home/dpc/.gnupg/S.gpg-agent': Invalid argument
** rdup-up: Failed to make socket `/home/dpc/tmp/home/dpc/.gnupg/S.gpg-agent.ssh': Invalid argument
** rdup-up: Failed to make socket `/home/dpc/tmp/home/dpc/.gnupg/S.scdaemon': Invalid argument
```

I wonder if:

* `rdup-up` could create them if it temporary changed permissions of the owning directory
* `rdup-up` could have a flag to skip errors like that (if there's nothing to do about them)

**Comment by miekg** [comment]
yeah, that doesn't make sense.

**Comment by dpc** [comment]
So the problem was that there's no way to restore a named socket and `mkfifo()` was failing.I guess #21 is enough of a fix.
