### ISSUE TITLE
HAVE_DIRFD works on OS X

### ISSUE THREAD

**Issue by ilovezfs** [miekg/rdup#25]
Currently configure.ac specifically disables HAVE_DIRFD for OS X, but that seems to work fine now, so the Homebrew formula patches it back in. It would be good if that could be avoided, and the configure.ac updated to treat OS X the same as any of the other platforms.

**Comment by miekg** [comment]
Agreed, please send a PR if possible

**Comment by ilovezfs** [comment]
Voilà https://github.com/miekg/rdup/pull/27

Is the repo ready for a new tag?

**Comment by miekg** [comment]
Yeah sure I'll tag it later today.

**Comment by ilovezfs** [comment]
@miekg Cool, thanks!

**Comment by ilovezfs** [comment]
@miekg Thanks for your help and the new tag. It's been merged to Homebrew master, and new binaries have been distributed. :)

https://github.com/Homebrew/homebrew/commit/961b6c917ea418f1adcca299e3d17d8952054b13
https://github.com/Homebrew/homebrew/commit/8cfd69cb33ecf5f799462fe448af1eb5d23585a7
https://github.com/Homebrew/homebrew/pull/49674
