### ISSUE TITLE
My 1.1.15 reports it's 1.1.14.

### ISSUE THREAD

**Issue by dpc** [miekg/rdup#28]
After brewing 1.1.15 with `brew upgrade rdup`:

```
/home/dpc/.linuxbrew/Cellar/rdup/1.1.15: 15 files, 221.7K, built in 8 seconds
dpc@spinlock ~/ (master) [I]> rdup -V
rdup 1.1.14
```

**Comment by miekg** [comment]
Ah damn. Then I forgot to up the version in the code... :(

**Comment by veox** [comment]
Looks like you tagged d66e432 as `1.1.15`, which is three commits before the string change in `configure.ac` (commit 02eb963).

I suggest you change the version strings to `1.1.16`, mention this issue to close it, tag that commit `1.1.16`, and push to github. This way, a new release is even warranted - you fixed a bug! :D

**Comment by dpc** [comment]
Even newer version was already released, so I don't think this one is worth fixing.
